version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
      - ./db-init/dev-db.sql:/data/application/init.sql
    env_file:
      - .env.db
    ports:
      - '3306:3306'

  mysql-test:
    image: mysql
    command: --init-file /data/application/init.sql
    volumes:
      - ./db-init/test-db.sql:/data/application/init.sql
    env_file:
      - .env.db
    ports:
      - '3307:3306'
