export const EnvVariables = {
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  PASSWORD_SALT: 'PASSWORD_SALT',
  MYSQL_HOST: 'MYSQL_HOST',
  MYSQL_PORT: 'MYSQL_PORT',
  MYSQL_USER: 'MYSQL_USER',
  MYSQL_PASSWORD: 'MYSQL_PASSWORD',
  MYSQL_DB: 'MYSQL_DB',
} as const;
